Inner block slider component
humanmade/hm-gutenberg-tools pull request #123
Opened 2022-10-13 13:51 UTC by mattheu

The inner block slider component is a utility component for managing sliders or carousels within the block editor. It uses inner blocks for each slide. It provides no front end JS or even any markup at all, so you can integrate it with whatever  front end implementation you choose.  

This is adapted from a 10up utility component. I couldn't actually get that working, so I fixed it as well as refectoring and modernizing it a bit. 

This is currently in use on another project.

2022-10-13 14:47 UTC, gonzomir requested changes
Great go see this component introduced here! Only one small thing - the `slidesPerPage` prop doesn't do anything and can be removed.

2022-10-13 14:47 UTC, gonzomir commented on js/inner-block-slider/index.js
> + * @param {number} root0.slidesPerPage - Number of visible slides.
This is not used any more, only one slide is visible at a time. Should this param be removed?

2022-10-13 14:47 UTC, gonzomir commented on js/inner-block-slider/index.js
> +	slidesPerPage: PropTypes.number,
Maybe remove if here too.

2022-10-13 14:59 UTC, mattheu commented
Thanks @gonzomir did a bit of cleanup.

2022-10-13 15:11 UTC, gonzomir commented on js/inner-block-slider/index.js
> +};
Oh, one more thing, should `slideLimit` appear also here?

2022-10-14 13:58 UTC, gonzomir approved these changes

2023-07-26 09:07 UTC, mattheu commented
This ended up being included in the [HM Block Editor Components library](https://github.com/humanmade/block-editor-components/tree/main/src/components/InnerBlockSlider) instead.

2023-07-26 09:07 UTC, closed without merging